name: Repository Dispatch
on:
  repository_dispatch:
    types: [systray-portable-release]
  push:
    branches:
      - master

jobs:
  update_releases:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_TOKEN }}

      - run: ls -la ./traybin

      - name: download new latest systray-portable binaries
        env:
          RELEASE_URL: https://github.com/one-click-studio/systray-portable/releases/download/latest
        run: |
          rm -rf ./traybin/tray_*
          curl -L $RELEASE_URL/tray-darwin-amd64      -o ./traybin/tray_darwin_release-amd64
          curl -L $RELEASE_URL/tray-darwin-arm64      -o ./traybin/tray_darwin_release-arm64
          curl -L $RELEASE_URL/tray-linux-amd64       -o ./traybin/tray_linux_release-amd64
          curl -L $RELEASE_URL/tray-linux-arm64       -o ./traybin/tray_linux_release-arm64
          curl -L $RELEASE_URL/tray-windows-amd64.exe -o ./traybin/tray_windows_release-amd64.exe
          chmod +x ./traybin/tray_*_release*

      - run: ls -la ./traybin

      - name: add and commit
        uses: EndBug/add-and-commit@v9
        with:
          add: './traybin/*'
          fetch: false
          author_name: tillderoquefeuil
          author_email: tillderoquefeuil@gmail.com
          message: 'Github Actions - update traybin binaries from latest systray-portable release'
          push: true

