name: Repository Dispatch
on:
  repository_dispatch:
    types: [systray-portable-release]
  push:
    branches:
      - master

  jobs:
    update_releases:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            ref: ${{ github.event.client_payload.ref }}
        - run: echo ${{ github.event.client_payload.sha }}
        - run: echo ${{ github.event.client_payload.ref }}